"""Generate ocean/wordle/wordle_words.h from a system dict.

Default source is /usr/share/dict/words. The generator filters to lowercase
five-letter ASCII words that contain at least two vowels, then evenly
samples NUM_WORDS of them across the alphabet for vocabulary diversity.

Usage:
    python ocean/wordle/gen_words.py
    python ocean/wordle/gen_words.py --num-words 4000
    python ocean/wordle/gen_words.py --source /path/to/wordlist.txt
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

VOWELS = frozenset("aeiou")


def candidate_words(source: Path) -> list[str]:
    out: list[str] = []
    with source.open() as f:
        for raw in f:
            w = raw.strip().lower()
            if len(w) != 5:
                continue
            if not w.isascii() or not w.isalpha():
                continue
            if sum(1 for c in w if c in VOWELS) < 2:
                continue
            out.append(w)
    out = sorted(set(out))
    if not out:
        sys.exit(f"gen_words.py: no candidates produced from {source}")
    return out


def even_sample(words: list[str], target: int) -> list[str]:
    if target >= len(words):
        return words
    step = len(words) / target
    picks = [words[int(i * step)] for i in range(target)]
    seen: set[str] = set()
    deduped: list[str] = []
    for w in picks:
        if w in seen:
            continue
        seen.add(w)
        deduped.append(w)
    return deduped


def emit_header(words: list[str], out_path: Path, source: Path, num_request: int) -> None:
    n = len(words)
    parts = [
        "/* Generated by ocean/wordle/gen_words.py. Do not edit by hand.\n",
        f" * Source:        {source}\n",
        f" * Requested:     {num_request} words\n",
        f" * Produced:      {n} words\n",
        " */\n",
        "#pragma once\n",
        "\n",
        "#define WORDLE_WORD_LEN 5\n",
        f"#define WORDLE_NUM_WORDS {n}\n",
        "\n",
    ]
    parts.append(
        "static const unsigned char WORDLE_WORDS[WORDLE_NUM_WORDS][WORDLE_WORD_LEN] = {\n",
    )
    for w in words:
        b = ", ".join(str(ord(c) - ord("a")) for c in w)
        parts.append(f"    {{ {b} }},  /* {w} */\n")
    parts.append("};\n")
    out_path.write_text("".join(parts))
    print(f"Wrote {out_path} ({n} words from {source})")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    here = Path(__file__).resolve().parent
    p.add_argument("--source", type=Path, default=Path("/usr/share/dict/words"))
    p.add_argument("--out", type=Path, default=here / "wordle_words.h")
    p.add_argument("--num-words", type=int, default=2315)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    if not args.source.exists():
        sys.exit(f"gen_words.py: source not found: {args.source}")
    candidates = candidate_words(args.source)
    selection = even_sample(candidates, args.num_words)
    os.makedirs(args.out.parent, exist_ok=True)
    emit_header(selection, args.out, args.source, args.num_words)


if __name__ == "__main__":
    main()
