/**
 * @fileoverview NPC model/animation mappings for encounter rendering.
 *
 * Maps NPC definition IDs to cache model IDs and animation sequence IDs.
 * Generated by scripts/export_inferno_npcs.py — do not edit.
 */

#ifndef NPC_MODELS_H
#define NPC_MODELS_H

#include <stdint.h>

typedef struct {
    uint16_t npc_id;
    uint32_t model_id;
    uint32_t idle_anim;
    uint32_t attack_anim;
    uint32_t walk_anim;    /* walk cycle animation; 65535 = use idle_anim */
} NpcModelMapping;

/* zulrah forms + snakeling */
static const NpcModelMapping NPC_MODEL_MAP_ZULRAH[] = {
    {2042, 14408, 5069, 5068, 65535},  /* green zulrah (ranged) */
    {2043, 14409, 5069, 5068, 65535},  /* red zulrah (melee) */
    {2044, 14407, 5069, 5068, 65535},  /* blue zulrah (magic) */
    {2045, 10415, 1721, 140, 2405},    /* snakeling melee */
    {2046, 10415, 1721, 185, 2405},    /* snakeling magic */
};

/* snakeling model + animations (NPC 2045 melee, 2046 magic — same model) */
#define SNAKELING_MODEL_ID 10415
#define SNAKELING_ANIM_IDLE    1721
#define SNAKELING_ANIM_MELEE   140   /* NPC 2045 melee attack */
#define SNAKELING_ANIM_MAGIC   185   /* NPC 2046 magic attack */
#define SNAKELING_ANIM_DEATH   138   /* NPC 2045 death */
#define SNAKELING_ANIM_WALK    2405  /* walk cycle */

/* zulrah spotanim (projectile/cloud) model IDs */
#define GFX_RANGED_PROJ_MODEL  20390  /* GFX 1044 ranged projectile */
#define GFX_CLOUD_PROJ_MODEL   11221  /* GFX 1045 cloud projectile */
#define GFX_MAGIC_PROJ_MODEL   26593  /* GFX 1046 magic projectile */
#define GFX_TOXIC_CLOUD_MODEL   4086  /* object 11700 */
#define GFX_SNAKELING_SPAWN_MODEL 20390  /* GFX 1047 spawn orb */

/* zulrah animation sequence IDs */
#define ZULRAH_ANIM_ATTACK   5068
#define ZULRAH_ANIM_IDLE     5069
#define ZULRAH_ANIM_DIVE     5072
#define ZULRAH_ANIM_SURFACE  5071
#define ZULRAH_ANIM_RISE     5073
#define ZULRAH_ANIM_5070     5070
#define ZULRAH_ANIM_5806     5806
#define ZULRAH_ANIM_5807     5807
#define GFX_SNAKELING_SPAWN_ANIM 5358

/* ================================================================ */
/* inferno NPC model/animation mappings (generated) */
#include "npc_models_inferno.h"

/* alias: encounter code uses NPC_MODEL_MAP_INFERNO, generated uses _GEN suffix */
#define NPC_MODEL_MAP_INFERNO NPC_MODEL_MAP_INFERNO_GEN

/* alias: encounter code uses INF_GFX_*, generated uses INF_GEN_GFX_* */
#define INF_GFX_157_MODEL   INF_GEN_GFX_157_MODEL
#define INF_GFX_157_ANIM    INF_GEN_GFX_157_ANIM
#define INF_GFX_448_MODEL   INF_GEN_GFX_448_MODEL
#define INF_GFX_448_ANIM    INF_GEN_GFX_448_ANIM
#define INF_GFX_449_MODEL   INF_GEN_GFX_449_MODEL
#define INF_GFX_449_ANIM    INF_GEN_GFX_449_ANIM
#define INF_GFX_450_MODEL   INF_GEN_GFX_450_MODEL
#define INF_GFX_450_ANIM    INF_GEN_GFX_450_ANIM
#define INF_GFX_659_MODEL   INF_GEN_GFX_659_MODEL
#define INF_GFX_659_ANIM    INF_GEN_GFX_659_ANIM
#define INF_GFX_660_MODEL   INF_GEN_GFX_660_MODEL
#define INF_GFX_660_ANIM    INF_GEN_GFX_660_ANIM
#define INF_GFX_451_MODEL   INF_GEN_GFX_451_MODEL
#define INF_GFX_451_ANIM    INF_GEN_GFX_451_ANIM
#define INF_GFX_1374_MODEL  INF_GEN_GFX_1374_MODEL
#define INF_GFX_1374_ANIM   INF_GEN_GFX_1374_ANIM
#define INF_GFX_1375_MODEL  INF_GEN_GFX_1375_MODEL
#define INF_GFX_1375_ANIM   INF_GEN_GFX_1375_ANIM
#define INF_GFX_1376_MODEL  INF_GEN_GFX_1376_MODEL
#define INF_GFX_1376_ANIM   INF_GEN_GFX_1376_ANIM
#define INF_GFX_1377_MODEL  INF_GEN_GFX_1377_MODEL
#define INF_GFX_1378_MODEL  INF_GEN_GFX_1378_MODEL
#define INF_GFX_1378_ANIM   INF_GEN_GFX_1378_ANIM
#define INF_GFX_1379_MODEL  INF_GEN_GFX_1379_MODEL
#define INF_GFX_1379_ANIM   INF_GEN_GFX_1379_ANIM
#define INF_GFX_1380_MODEL  INF_GEN_GFX_1380_MODEL
#define INF_GFX_1380_ANIM   INF_GEN_GFX_1380_ANIM
#define INF_GFX_1381_MODEL  INF_GEN_GFX_1381_MODEL
#define INF_GFX_1381_ANIM   INF_GEN_GFX_1381_ANIM
#define INF_GFX_1382_MODEL  INF_GEN_GFX_1382_MODEL
#define INF_GFX_1382_ANIM   INF_GEN_GFX_1382_ANIM
#define INF_GFX_1383_MODEL  INF_GEN_GFX_1383_MODEL
#define INF_GFX_1383_ANIM   INF_GEN_GFX_1383_ANIM
#define INF_GFX_1384_MODEL  INF_GEN_GFX_1384_MODEL
#define INF_GFX_1385_MODEL  INF_GEN_GFX_1385_MODEL
#define INF_GFX_1385_ANIM   INF_GEN_GFX_1385_ANIM
#define INF_GFX_1120_MODEL  INF_GEN_GFX_1120_MODEL
#define INF_GFX_1120_ANIM   INF_GEN_GFX_1120_ANIM

/* inferno spotanim ids for shared render/event wiring */
#define INF_GFX_659_ID  659
#define INF_GFX_660_ID  660
#define INF_GFX_1120_ID  1120

/* inferno pillar models — Rocky support objects 30284-30287 */
#define INF_PILLAR_MODEL_100  33044  /* object 30284 — full health */
#define INF_PILLAR_MODEL_75   33043  /* object 30285 — 75% HP */
#define INF_PILLAR_MODEL_50   33042  /* object 30286 — 50% HP */
#define INF_PILLAR_MODEL_25   33045  /* object 30287 — 25% HP */

static const NpcModelMapping* npc_model_lookup(uint16_t npc_id) {
    for (int i = 0; i < (int)(sizeof(NPC_MODEL_MAP_ZULRAH) / sizeof(NPC_MODEL_MAP_ZULRAH[0])); i++) {
        if (NPC_MODEL_MAP_ZULRAH[i].npc_id == npc_id) return &NPC_MODEL_MAP_ZULRAH[i];
    }
    for (int i = 0; i < (int)(sizeof(NPC_MODEL_MAP_INFERNO_GEN) / sizeof(NPC_MODEL_MAP_INFERNO_GEN[0])); i++) {
        if (NPC_MODEL_MAP_INFERNO_GEN[i].npc_id == npc_id) return &NPC_MODEL_MAP_INFERNO_GEN[i];
    }
    return NULL;
}

#endif /* NPC_MODELS_H */
