/* generated by tools/export_encounter_npcs.py -- do not edit */
#ifndef NPC_MODELS_ZULRAH_H
#define NPC_MODELS_ZULRAH_H

#include <stdint.h>
#include "npc_models.h"  /* for NpcModelMapping typedef */

static const NpcModelMapping NPC_MODEL_MAP_ZULRAH_GEN[] = {
    {2042, 0xC07FA, 5070, 5068, 5070},  /* Zulrah green/ranged form */
    {2043, 0xC07FB, 5070, 5806, 5070},  /* Zulrah red/melee form */
    {2044, 0xC07FC, 5070, 5068, 5070},  /* Zulrah blue/magic form */
    {2045, 0xC07FD, 1721, 65535, 2405},  /* Snakeling melee variant */
    {2046, 0xC07FE, 1721, 65535, 2405},  /* Snakeling magic variant */
};

/* zulrah animation IDs */
#define ZUL_GEN_ANIM_SNAKEBOSS_ATTACK_ACIDX3  5068
#define ZUL_GEN_ANIM_SNAKEBOSS_ATTACK_ACIDX1  5069
#define ZUL_GEN_ANIM_SNAKEBOSS_SPAWN  5071
#define ZUL_GEN_ANIM_SNAKEBOSS_SINKFAST  5072
#define ZUL_GEN_ANIM_SNAKEBOSS_EMERGEFAST  5073
#define ZUL_GEN_ANIM_SNAKEBOSS_DEATH  5804
#define ZUL_GEN_ANIM_SNAKEBOSS_ATTACK_TAIL_LEFT  5806
#define ZUL_GEN_ANIM_SNAKEBOSS_ATTACK_TAIL_RIGHT  5807
#define ZUL_GEN_ANIM_SNAKEBOSS_DEFEND  5808

/* zulrah spotanim GFX model + animation IDs */
#define ZUL_GEN_GFX_1044_MODEL  853012  /* SNAKEBOSS_ORB */
#define ZUL_GEN_GFX_1044_ANIM   5358
#define ZUL_GEN_GFX_1045_MODEL  853013  /* SNAKEBOSS_DOUBLE_ORB */
#define ZUL_GEN_GFX_1045_ANIM   3151
#define ZUL_GEN_GFX_1046_MODEL  853014  /* SNAKEBOSS_FIREBALL */
#define ZUL_GEN_GFX_1046_ANIM   6648
#define ZUL_GEN_GFX_1047_MODEL  853015  /* SNAKEBOSS_EGG */
#define ZUL_GEN_GFX_1047_ANIM   5358
#define ZUL_GEN_GFX_1230_MODEL  853198  /* SNAKEBOSS_MINION_SPELL */
#define ZUL_GEN_GFX_1230_ANIM   703

#endif /* NPC_MODELS_ZULRAH_H */
