/* generated by scripts/export_models.py — do not edit */
#ifndef PLAYER_MODELS_H
#define PLAYER_MODELS_H

#include <stdint.h>

/* body part indices (male) */
#define BODY_PART_HEAD 0
#define BODY_PART_JAW 1
#define BODY_PART_TORSO 2
#define BODY_PART_ARMS 3
#define BODY_PART_HANDS 4
#define BODY_PART_LEGS 5
#define BODY_PART_FEET 6
#define BODY_PART_COUNT 7

/* default male body part model IDs (synthetic: 0xF0000 + part_id) */
static const uint32_t DEFAULT_BODY_MODELS[BODY_PART_COUNT] = {
    0xF0000,  /* HEAD */
    0xF0001,  /* JAW */
    0xF0002,  /* TORSO */
    0xF0003,  /* ARMS */
    0xF0004,  /* HANDS */
    0xF0005,  /* LEGS */
    0xF0006,  /* FEET */
};

#endif /* PLAYER_MODELS_H */
