[base]
env_name = boxoban

[vec]
total_agents = 32768
num_buffers = 4
num_threads = 1

[env]
num_agents = 1
difficulty = 2
int_r_coeff = 0.25
max_steps = 150

[policy]
hidden_size = 512
num_layers = 3.32422
expansion_factor = 1

[train]
gpus = 1
seed = 42
total_timesteps = 880580001
learning_rate = 0.00134234
anneal_lr = 1
min_lr_ratio = 0.37872
gamma = 0.989717
gae_lambda = 0.759273
state_lambda = 0.759273
replay_ratio = 1.6234
clip_coef = 0.01
vf_coef = 5
vf_clip_coef = 5
max_grad_norm = 1.20325
ent_coef = 0.000188411
beta1 = 0.995526
beta2 = 0.999536
eps = 1e-14
minibatch_size = 32768
horizon = 64
vtrace_rho_clip = 3.13347
vtrace_c_clip = 2.75328
prio_alpha = 0.453827
prio_beta0 = 0.765589
state_buffer_size = 8112.93
cl_frac = 0.57991
anneal_cl = 0
warmup_states = 100
state_checkpoint_interval = 16
explore_alpha = 1
explore_beta = 0
explore_decay = 0.99
state_priority_decay = 0.99

#state_buffer_size = 1000
#cl_frac = 0.50
#anneal_cl = 0
#warmup_states = 100
#state_checkpoint_interval = 16
#explore_alpha = 1.0
#explore_beta = 0.0
#explore_decay = 0.98

#prio_alpha = 0
#prio_beta0 = 0
#anneal_prio_beta = 0
#state_buffer_size = 100
#cl_frac = 0.350092
#anneal_cl = 0
#warmup_states = 100
#state_checkpoint_interval = 16
#explore_alpha = 0.149763
#explore_beta = 0.172232
#explore_decay = 0.967679

[sweep]
max_suggestion_cost = 10800

[sweep.train.state_buffer_size]
distribution = uniform
min = 100
max = 20_000
scale = auto

[sweep.train.cl_frac]
distribution = uniform
min = 0.0
max = 0.8
scale = auto

[sweep.train.explore_alpha]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.train.explore_beta]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.train.explore_decay]
distribution = logit_normal
min = 0.5
max = 0.999
scale = auto
