[base]
package = ocean
env_name = password

[vec]
total_agents = 8192
num_buffers = 4
num_threads = 4

#[policy]
#hidden_size = 256
#num_layers = 1
#expansion_factor = 1

[train]
gpus = 1
seed = 42
total_timesteps = 200_000_000
minibatch_size = 8192
#total_timesteps = 205259002
#learning_rate = 0.00993891
#anneal_lr = 1
#min_lr_ratio = 0
#gamma = 0.998755
#gae_lambda = 0.995
#replay_ratio = 4
#clip_coef = 0.19359
#vf_coef = 3.50617
#vf_clip_coef = 0.01
#max_grad_norm = 0.1
#ent_coef = 0.2
#anneal_ent_coef = 0
#min_ent_coef_ratio = 0.1
#momentum = 0.861029
#eps = 2.62761e-11
#minibatch_size = 32768
#vtrace_rho_clip = 2.76586
#vtrace_c_clip = 0.600952
#prio_alpha = 0.477338
#prio_beta0 = 0.746417
#prio_alpha = 0.0
#prio_beta0 = 0.0
state_buffer_size = 100_000
cl_frac = 0.8
anneal_cl = 1
warmup_states = 100_000
state_lambda = 0.90
prio_alpha = 0.0
prio_beta0 = 0.0
explore_alpha = 0.99
state_priority_decay = 0.99
#explore_beta = 0.0
