#ifndef OSRS_GFX_IDS_H
#define OSRS_GFX_IDS_H

// Lunar vengeance cast flash on the caster (footage spotanim 726).
#define GFX_VENGEANCE       726
// Teleport-tablet break flash (deob POH_SMASH_MAGIC_TABLET 4069 / gfx 678).
#define GFX_TELEPORT_BREAK  678
#define GFX_RUNE_ARROW_LAUNCH 24
#define GFX_SPLASH          85
#define GFX_TRIDENT_CAST    665
#define GFX_TRIDENT_PROJ    1040
#define GFX_TRIDENT_IMPACT  1042
#define GFX_TUMEKENS_SHADOW_CAST   2125
#define GFX_TUMEKENS_SHADOW_PROJ   2126
#define GFX_TUMEKENS_SHADOW_IMPACT 2127
#define GFX_BLOWPIPE_SPEC   1043
#define GFX_DRAGON_ARROW_LAUNCH 1116
#define GFX_DRAGON_DART     1122

#define GFX_COLOSSEUM_JAVELIN_SKYFALL_LAUNCH_TRAVEL 2674
#define GFX_COLOSSEUM_JAVELIN_SKYFALL_DROP_TRAVEL   2675
#define GFX_COLOSSEUM_JAVELIN_SKYFALL_IMPACT        2676
#define GFX_COLOSSEUM_SOL_SPHERE_TRAVEL 2693
#define GFX_COLOSSEUM_SOL_SPHERE_IMPACT 2697
#define GFX_COLOSSEUM_SOL_DUST_BASE  2699
#define GFX_COLOSSEUM_SOL_DUST_COUNT 8
#define GFX_COLOSSEUM_VOLATILITY_HUMAN_EXPLOSION     2713
#define GFX_COLOSSEUM_VOLATILITY_MANTICORE_EXPLOSION 2721
#define GFX_COLOSSEUM_VOLATILITY_COLOSSUS_EXPLOSION  2722
#define GFX_COLOSSEUM_VOLATILITY_MINOTAUR_EXPLOSION  2723
#define GFX_COLOSSEUM_VOLATILITY_SOL_EXPLOSION       2724
#define MODEL_COLOSSEUM_SOL_CRYSTAL_CHARGE 51245
#define ANIM_COLOSSEUM_SOL_CRYSTAL_CHARGE  10803
#define MODEL_COLOSSEUM_SOL_SAND_PILLAR    51243
#define ANIM_COLOSSEUM_SOL_SAND_PILLAR     10812

#define ANIM_SEQ_IDLE           808
#define ANIM_SEQ_WALK           819
#define ANIM_SEQ_RUN            824
#define ANIM_SEQ_EAT            829
#define ANIM_SEQ_DEATH          836
#define ANIM_SEQ_CAST_STANDARD  1162
#define ANIM_SEQ_CAST_BARRAGE   1979
#define ANIM_SEQ_CAST_VENG      8317
#define ANIM_SEQ_TAB_BREAK      4069
#define ANIM_SEQ_BLOCK_SHIELD   1156
#define ANIM_SEQ_BLOCK_MELEE    424

#endif
