#ifndef OSRS_NPC_MODELS_H
#define OSRS_NPC_MODELS_H

#include "data/npc_models_zulrah.h"
#include "data/npc_models_inferno.h"
#include "data/npc_models_colosseum.h"

#define SNAKELING_MODEL_MELEE  (OSRS_NPC_MODEL_BASE | 2045u)
#define SNAKELING_MODEL_MAGIC  (OSRS_NPC_MODEL_BASE | 2046u)
#define SNAKELING_ANIM_IDLE    SEQ_ZULRAH_SNAKEBOSS_PET_IDLE
#define SNAKELING_ANIM_MELEE   SEQ_ZULRAH_GIANTRAT_READY
#define SNAKELING_ANIM_MAGIC   SEQ_ZULRAH_MAGICAXE_ATTACK
#define SNAKELING_ANIM_DEATH   SEQ_ZULRAH_GIANTRAT_ATTACK
#define SNAKELING_ANIM_WALK    SEQ_ZULRAH_SNAKEBOSS_PET_WALK_FORWARD

#define GFX_RANGED_PROJ_MODEL  SPOTANIM_ZULRAH_SNAKEBOSS_ORB
#define GFX_RANGED_PROJ_ANIM   SPOTANIM_ZULRAH_SNAKEBOSS_ORB_ANIM
#define GFX_CLOUD_PROJ_MODEL   SPOTANIM_ZULRAH_SNAKEBOSS_DOUBLE_ORB
#define GFX_CLOUD_PROJ_ANIM    SPOTANIM_ZULRAH_SNAKEBOSS_DOUBLE_ORB_ANIM
#define GFX_MAGIC_PROJ_MODEL   SPOTANIM_ZULRAH_SNAKEBOSS_FIREBALL
#define GFX_MAGIC_PROJ_ANIM    SPOTANIM_ZULRAH_SNAKEBOSS_FIREBALL_ANIM
#define GFX_TOXIC_CLOUD_MODEL  LOC_ZULRAH_SNAKEBOSS_POISONCLOUD
#define GFX_SNAKELING_SPAWN_MODEL SPOTANIM_ZULRAH_SNAKEBOSS_EGG
#define GFX_SNAKELING_SPAWN_ANIM  SPOTANIM_ZULRAH_SNAKEBOSS_EGG_ANIM

#define ZULRAH_ANIM_ATTACK        SEQ_ZULRAH_SNAKEBOSS_ATTACK_ACIDX3
#define ZULRAH_ANIM_ATTACK_MAGIC  SEQ_ZULRAH_SNAKEBOSS_ATTACK_ACIDX1
#define ZULRAH_ANIM_IDLE          SEQ_ZULRAH_SNAKEBOSS_IDLE
#define ZULRAH_ANIM_DIVE          SEQ_ZULRAH_SNAKEBOSS_SINKFAST
#define ZULRAH_ANIM_SURFACE       SEQ_ZULRAH_SNAKEBOSS_SPAWN
#define ZULRAH_ANIM_RISE          SEQ_ZULRAH_SNAKEBOSS_EMERGEFAST
#define ZULRAH_ANIM_TAIL_LEFT     SEQ_ZULRAH_SNAKEBOSS_ATTACK_TAIL_LEFT
#define ZULRAH_ANIM_TAIL_RIGHT    SEQ_ZULRAH_SNAKEBOSS_ATTACK_TAIL_RIGHT
#define ZULRAH_ANIM_DEATH         SEQ_ZULRAH_SNAKEBOSS_DEATH
#define ZULRAH_ANIM_DEFEND        SEQ_ZULRAH_SNAKEBOSS_DEFEND

#define NPC_MODEL_MAP_INFERNO NPC_MODEL_MAP_INFERNO_GEN

#define INF_GFX_157_MODEL   SPOTANIM_INFERNO_FIREWAVE_IMPACT
#define INF_GFX_157_ANIM    SPOTANIM_INFERNO_FIREWAVE_IMPACT_ANIM
#define INF_GFX_448_MODEL   SPOTANIM_INFERNO_TZHAAR_FIRE_SPIT_TRAVEL
#define INF_GFX_448_ANIM    SPOTANIM_INFERNO_TZHAAR_FIRE_SPIT_TRAVEL_ANIM
#define INF_GFX_449_MODEL   SPOTANIM_INFERNO_TZHAAR_FIRE_SPIT_FOLLOW_TRAVEL
#define INF_GFX_449_ANIM    SPOTANIM_INFERNO_TZHAAR_FIRE_SPIT_FOLLOW_TRAVEL_ANIM
#define INF_GFX_450_MODEL   SPOTANIM_INFERNO_TZHAAR_FIRE_SPIT_END_TRAVEL
#define INF_GFX_450_ANIM    SPOTANIM_INFERNO_TZHAAR_FIRE_SPIT_END_TRAVEL_ANIM
#define INF_GFX_659_MODEL   SPOTANIM_INFERNO_WILD_FALLOFF_METEOR_BLAST
#define INF_GFX_659_ANIM    SPOTANIM_INFERNO_WILD_FALLOFF_METEOR_BLAST_ANIM
#define INF_GFX_660_MODEL   SPOTANIM_INFERNO_WILD_FALLOFF_METEOR_FLYING
#define INF_GFX_660_ANIM    SPOTANIM_INFERNO_WILD_FALLOFF_METEOR_FLYING_ANIM
#define INF_GFX_451_MODEL   SPOTANIM_INFERNO_TZHAAR_ROCK_SMASH
#define INF_GFX_451_ANIM    SPOTANIM_INFERNO_TZHAAR_ROCK_SMASH_ANIM
#define INF_GFX_1374_MODEL  SPOTANIM_INFERNO_SLAYER_MAGICDART_ENCHANTED_IMPACT
#define INF_GFX_1374_ANIM   SPOTANIM_INFERNO_SLAYER_MAGICDART_ENCHANTED_IMPACT_ANIM
#define INF_GFX_1375_MODEL  SPOTANIM_INFERNO_INFERNO_ZUK_PROJECTILE
#define INF_GFX_1375_ANIM   SPOTANIM_INFERNO_INFERNO_ZUK_PROJECTILE_ANIM
#define INF_GFX_1376_MODEL  SPOTANIM_INFERNO_INFERNO_ZEK_PROJECTILE
#define INF_GFX_1376_ANIM   SPOTANIM_INFERNO_INFERNO_ZEK_PROJECTILE_ANIM
#define INF_GFX_1377_MODEL  SPOTANIM_INFERNO_INFERNO_XIL_PROJECTILE
#define INF_GFX_1378_MODEL  SPOTANIM_INFERNO_INFERNO_SPLITTER_RANGE
#define INF_GFX_1378_ANIM   SPOTANIM_INFERNO_INFERNO_SPLITTER_RANGE_ANIM
#define INF_GFX_1379_MODEL  SPOTANIM_INFERNO_INFERNO_BABYSPLITTER_RANGE
#define INF_GFX_1379_ANIM   SPOTANIM_INFERNO_INFERNO_BABYSPLITTER_RANGE_ANIM
#define INF_GFX_1380_MODEL  SPOTANIM_INFERNO_INFERNO_SPLITTER_MAGE
#define INF_GFX_1380_ANIM   SPOTANIM_INFERNO_INFERNO_SPLITTER_MAGE_ANIM
#define INF_GFX_1381_MODEL  SPOTANIM_INFERNO_INFERNO_BABYSPLITTER_MAGE
#define INF_GFX_1381_ANIM   SPOTANIM_INFERNO_INFERNO_BABYSPLITTER_MAGE_ANIM
#define INF_GFX_1382_MODEL  SPOTANIM_INFERNO_INFERNO_HARPIE_PROJ
#define INF_GFX_1382_ANIM   SPOTANIM_INFERNO_INFERNO_HARPIE_PROJ_ANIM
#define INF_GFX_1383_MODEL  SPOTANIM_INFERNO_DOUBLE_AMETHYST_ARROW_LAUNCH
#define INF_GFX_1383_ANIM   SPOTANIM_INFERNO_DOUBLE_AMETHYST_ARROW_LAUNCH_ANIM
#define INF_GFX_1384_MODEL  SPOTANIM_INFERNO_AMETHYST_ARROW_TRAVEL
#define INF_GFX_1385_MODEL  SPOTANIM_INFERNO_AMETHYST_ARROW_LAUNCH
#define INF_GFX_1385_ANIM   SPOTANIM_INFERNO_AMETHYST_ARROW_LAUNCH_ANIM
#define INF_GFX_1120_MODEL  SPOTANIM_INFERNO_II_DRAGON_ARROW_NORMAL_PROJANIM
#define INF_GFX_1120_ANIM   SPOTANIM_INFERNO_II_DRAGON_ARROW_NORMAL_PROJANIM_ANIM


#define INF_GFX_659_ID  659
#define INF_GFX_660_ID  660
#define INF_GFX_1120_ID  1120

#define INF_PILLAR_MODEL_100  LOC_INFERNO_INFERNO_SAFESPOT_100
#define INF_PILLAR_MODEL_75   LOC_INFERNO_INFERNO_SAFESPOT_75
#define INF_PILLAR_MODEL_50   LOC_INFERNO_INFERNO_SAFESPOT_50
#define INF_PILLAR_MODEL_25   LOC_INFERNO_INFERNO_SAFESPOT_25

static const NpcModelMapping* npc_model_lookup(uint16_t npc_id) {
    static const struct { const NpcModelMapping* rows; size_t count; } packs[] = {
        {NPC_MODEL_MAP_ZULRAH_GEN, sizeof(NPC_MODEL_MAP_ZULRAH_GEN) / sizeof(*NPC_MODEL_MAP_ZULRAH_GEN)},
        {NPC_MODEL_MAP_INFERNO_GEN, sizeof(NPC_MODEL_MAP_INFERNO_GEN) / sizeof(*NPC_MODEL_MAP_INFERNO_GEN)},
        {NPC_MODEL_MAP_COLOSSEUM_GEN, sizeof(NPC_MODEL_MAP_COLOSSEUM_GEN) / sizeof(*NPC_MODEL_MAP_COLOSSEUM_GEN)},
    };
    for (size_t p = 0; p < sizeof(packs) / sizeof(*packs); p++)
        for (size_t i = 0; i < packs[p].count; i++)
            if (packs[p].rows[i].npc_id == npc_id) return &packs[p].rows[i];
    return NULL;
}

#endif
