#ifndef OSRS_COMBAT_VISUALS_LOCAL_H
#define OSRS_COMBAT_VISUALS_LOCAL_H

#define OSRS_CV_MISSING OSRS_COMBAT_PROJECTILE_MISSING
#define OSRS_CV_NONE \
    {OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, 1}
#define OSRS_CV_LAUNCH(gfx) \
    {gfx, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, 1}
#define OSRS_CV_IMPACT(launch, impact) \
    {launch, OSRS_CV_MISSING, impact, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, 1}
#define OSRS_CV_TRAVEL(launch, travel, impact, model, anim, hit, client, start, end, delay, angle, len, progress, step, count) \
    {launch, travel, impact, model, anim, hit, client, start, end, delay, angle, \
     len, progress, step, count}
#define OSRS_CV_ALT_NONE \
    {OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING}
#define OSRS_CV_SPECIAL(item, style, anim, projectile) \
    {OSRS_COMBAT_VISUAL_KIND_SPECIAL, item, "", style, \
     OSRS_COMBAT_VISUAL_STANCE_ANY, anim, projectile, OSRS_CV_ALT_NONE, \
     OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, OSRS_CV_MISSING, \
     0, OSRS_CV_MISSING}

static const OsrsCombatVisualRow OSRS_COMBAT_VISUAL_LOCAL_ROWS[] = {
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_GRANITE_MAUL, ATTACK_STYLE_MELEE,
        1667, OSRS_CV_LAUNCH(340)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_DRAGON_CLAWS, ATTACK_STYLE_MELEE,
        7514, OSRS_CV_LAUNCH(1171)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_STATIUSS_WARHAMMER, ATTACK_STYLE_MELEE,
        1378, OSRS_CV_LAUNCH(844)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_VESTAS_LONGSWORD, ATTACK_STYLE_MELEE,
        7515, OSRS_CV_NONE),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_ANCIENT_GODSWORD, ATTACK_STYLE_MELEE,
        9171, OSRS_CV_LAUNCH(1996)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_VOIDWAKER, ATTACK_STYLE_MELEE,
        11275, OSRS_CV_IMPACT(2834, 2363)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_ARMADYL_CROSSBOW, ATTACK_STYLE_RANGED,
        4230, OSRS_CV_LAUNCH(301)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_ZARYTE_CROSSBOW, ATTACK_STYLE_RANGED,
        9166, OSRS_CV_LAUNCH(1995)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_MORRIGANS_JAVELIN, ATTACK_STYLE_RANGED,
        11467, OSRS_CV_TRAVEL(2919, 2920, OSRS_CV_MISSING, 54231, 11472,
            2, 2, 163, 146, 32, 15, 0, 11, 5, 1)),
    OSRS_CV_SPECIAL(OSRS_ITEM_ID_VOLATILE_NIGHTMARE_STAFF, ATTACK_STYLE_MAGIC,
        8532, OSRS_CV_IMPACT(1760, 1759)),
};

static const size_t OSRS_COMBAT_VISUAL_LOCAL_ROW_COUNT =
    sizeof(OSRS_COMBAT_VISUAL_LOCAL_ROWS) /
    sizeof(OSRS_COMBAT_VISUAL_LOCAL_ROWS[0]);

#undef OSRS_CV_SPECIAL
#undef OSRS_CV_ALT_NONE
#undef OSRS_CV_TRAVEL
#undef OSRS_CV_IMPACT
#undef OSRS_CV_LAUNCH
#undef OSRS_CV_NONE
#undef OSRS_CV_MISSING

#endif
